baseURL: "https://mypaceshun.github.io/blog/"
languageCode: "ja-jp"
#defaultContentLanguage: ja
title: "mypaceshun blog"
theme: "beautifulhugo"
canonifyurls: true
disqusShortname: https-mypaceshun-github-io-blog
googleAnalytics: G-G00JGTHDLH
publishdir: "docs/"
permalinks:
  posts: /:year/:month/:filename/

params:
  subtitle: "mypaceshunの独り言ブログ"
  mainSections:
    - posts
  logo: "images/mypaceshun.png"
  favicon: "images/favicon.ico"
  commit: true
  rss: true
  comments: true
  readingTime: true
  socialShare: true
  delayDisqus: false

author:
  name: "KAWAI Shun"
  website: https://mypaceshun.github.io/blog/
  github: mypaceshun
  twitter: rikanodorei_823
  instagram: rikanodorei

menu:
  main:
    - identifier: about
      name: about me
      url: /page/about/
